logging:
  level:
    root: DEBUG
spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:1000

server:
  port: 6161

management:
  tracing:
    sampling:
      probability: 1.0
  


  