spring:
   application:
       name: gateway-service
   config:
     import: optional:configserver:http://localhost:1000


server:
  port: 7171
management:
  tracing:
    sampling:
      probability: 1.0




