logging:
  level:
    root: DEBUG
spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:1000
server:
  port: 5151

management:
  tracing:
    sampling:
      probability: 1.0