spring:
  application:
     name: customer-service
  config:
    import: optional:configserver:http://localhost:1000

server:
  port: 2121

management:
  tracing:
    sampling:
      probability: 1.0

